package com.greywolf.community.model;

public class comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.gmCreatC
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private Long gmcreatc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.creator
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comWhoID
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private Integer comwhoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.likenCount
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    private Integer likencount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment
     *
     * @return the value of comments.comment
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment
     *
     * @param comment the value for comments.comment
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.gmCreatC
     *
     * @return the value of comments.gmCreatC
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public Long getGmcreatc() {
        return gmcreatc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.gmCreatC
     *
     * @param gmcreatc the value for comments.gmCreatC
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setGmcreatc(Long gmcreatc) {
        this.gmcreatc = gmcreatc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.creator
     *
     * @return the value of comments.creator
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.creator
     *
     * @param creator the value for comments.creator
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comWhoID
     *
     * @return the value of comments.comWhoID
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public Integer getComwhoid() {
        return comwhoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comWhoID
     *
     * @param comwhoid the value for comments.comWhoID
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setComwhoid(Integer comwhoid) {
        this.comwhoid = comwhoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.likenCount
     *
     * @return the value of comments.likenCount
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public Integer getLikencount() {
        return likencount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.likenCount
     *
     * @param likencount the value for comments.likenCount
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    public void setLikencount(Integer likencount) {
        this.likencount = likencount;
    }
}