package com.greywolf.community.mapper;

import com.greywolf.community.model.comments;
import com.greywolf.community.model.commentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface commentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    long countByExample(commentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int deleteByExample(commentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int insert(comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int insertSelective(comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<comments> selectByExampleWithRowbounds(commentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<comments> selectByExample(commentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    comments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") comments record, @Param("example") commentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByExample(@Param("record") comments record, @Param("example") commentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByPrimaryKeySelective(comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByPrimaryKey(comments record);
}