package com.greywolf.community.mapper;

import com.greywolf.community.model.topicQuestion;
import com.greywolf.community.model.topicQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface topicQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    long countByExample(topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int deleteByExample(topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int insert(topicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int insertSelective(topicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<topicQuestion> selectByExampleWithBLOBsWithRowbounds(topicQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<topicQuestion> selectByExampleWithBLOBs(topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<topicQuestion> selectByExampleWithRowbounds(topicQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    List<topicQuestion> selectByExample(topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    topicQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") topicQuestion record, @Param("example") topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") topicQuestion record, @Param("example") topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByExample(@Param("record") topicQuestion record, @Param("example") topicQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByPrimaryKeySelective(topicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(topicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicquestion
     *
     * @mbg.generated Sat Mar 14 17:55:12 CST 2020
     */
    int updateByPrimaryKey(topicQuestion record);
}